Backend/Models/Register_1ViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BackEnd.Models;

public class Register_1ViewModel
{
    [Required]
    [StringLength(255, ErrorMessage = "La longitud del nombre debe ser menos que {0}")]
    public string Nombre { get; set; }
    [Required]
    [StringLength(255, ErrorMessage = "La longitud del apellido debe ser menos que {0}")]
    public string Apellido { get; set; }
    [Required]
    [StringLength(255, ErrorMessage = "La longitud del NombreUsuario debe ser menos que {0}")]
    public string NombreUsuario { get; set; }

}

Backend/Models/Register_2ViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BackEnd.Models;

public class Register_2ViewModel
{
    [Required]
    [EmailAddress(ErrorMessage = "El formato del correo no es válido.")]
    public string Email { get; set; }
    
    [Required(ErrorMessage = "La contraseña es obligatoria.")]
    public string Contrasena { get; set; }

    [Required]
    [Compare("Contrasena", ErrorMessage = "Las contraseñas no coinciden.")]
    public string RepetirContrasena { get; set; }
}

Backend/Controllers/RegisterController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BackEnd.Interface;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using BackEnd.Models;
using Microsoft.AspNetCore.Authentication;

namespace BackEnd.Controllers;

public class RegisterController : Controller
{
    private readonly IRepoUsuario _repoUsuario;
    private readonly IRepoRolUsuario _repoRolUsuario;
    public RegisterController(IRepoUsuario repoUsuario, IRepoRolUsuario repoRolUsuario)
    {
        _repoUsuario = repoUsuario;
        _repoRolUsuario = repoRolUsuario;
    }

    [HttpGet]
    public IActionResult Register_1()
    {
        if(User.Identity.IsAuthenticated)
        {
            return RedirectToAction("Index", "Home");
        }
        return View();
    }

    [HttpPost]
    public IActionResult Register_1(Register_1ViewModel model)
    {
        if(ModelState.IsValid)
        {
            var nombreUsuarioExistente = _repoUsuario.SelectWhere(u => u.NombreUsuario == model.NombreUsuario);
            if(nombreUsuarioExistente.Any())
            {
                ModelState.AddModelError("NombreUsuario", "El nombre usuario ya esta en uso. Por favor, elige otro.");
                return View(model);
            }
            else
            {
                TempData["Nombre"] = model.Nombre;
                TempData["Apellido"] = model.Apellido;
                TempData["NombreUsuario"] = model.NombreUsuario;

                return RedirectToAction("Register_2");
            }
        }
        else
        {
            return View(model);
        }
    }

    [HttpGet]
    public IActionResult Register_2()
    {
        if(User.Identity.IsAuthenticated)
        {
            return RedirectToAction("Index", "Home");
        }
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register_2(Register_2ViewModel model)
    {
        if (ModelState.IsValid)
        {
            var mailExistente = _repoUsuario.SelectWhere(u => u.Email == model.Email).FirstOrDefault();
            if(mailExistente != null)
            {
                ModelState.AddModelError("Email", "El email ya está en uso. Por favor, elige otro.");
                return View(model);
            }
            else
            {                
                var rol = _repoRolUsuario.IdSelect(1);

                var usuario = new Usuario
                {
                    Email = model.Email,
                    Contrasena = BCrypt.Net.BCrypt.HashPassword(model.Contrasena),
                    Apellido = TempData["Apellido"].ToString(),
                    Nombre = TempData["Nombre"].ToString(),
                    NombreUsuario = TempData["NombreUsuario"].ToString(),
                    FotoPerfil = "",
                    IdRol =  1,
                    IdUsuario = 0,
                    Rol = rol
                };

                var idAutoIncrementado = _repoUsuario.Insert(usuario, "IdUsuario");
                usuario.IdUsuario = idAutoIncrementado;

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, usuario.IdUsuario.ToString()),
                    new Claim(ClaimTypes.Name, usuario.NombreUsuario.ToString()),
                    new Claim(ClaimTypes.Email, usuario.Email),
                    new Claim(ClaimTypes.Role, rol.Descripcion)
                };

                // Crear la identidad y el principal
                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);    
                return RedirectToAction("Index", "Home");
            }
        }
        else
        {
            return View(model);
        }
        
    }

    public IActionResult Privacy()
    {
        return View();
    }
    public IActionResult Login()
    {
        return RedirectToAction("Login", "Login");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Backend/Views/Register/Register_1.cshtml
@model BackEnd.Models.Register_1ViewModel;
<body id="body" class="h-screen w-full flex justify-center">
    <section class="h-full w-5/12 flex justify-center items-center">
        <div id="login" class="flex flex-col items-center h-4/5 w-full text-xl font-bold text-white rounded-3xl text-center bg-white/50">
            <h1 class="mt-8 mb-12 text-4xl font-bold">Registrate</h1>
            <form asp-action = "Register_1" asp-controller="Register" class="w-4/6 mt-6 flex justify-center items-center flex-col" method="post">
                
                <p class="mb-2">Nombre</p>
                <!--Input de Nombre-->
                <div class="w-4/5 relative">
                    <label for="Nombre"></label>
                    <input asp-for="Nombre" class="pl-12 text-black w-full h-12 rounded-full bg-white outline-none" name="Nombre" type="text" required >
                    <svg class="absolute pr-2" id="usuario" data-name="Capa 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 125.71 170.52">
                        <circle class="cls-1" cx="62.86" cy="40.81" r="37.31"/>
                        <path class="cls-1" d="M62.86,166.97s49.73,2.37,59.26-26.52c2.93-63.17-59.26-62.32-59.26-62.32,0,0-62.18-.84-59.26,62.32,9.52,28.89,59.26,26.52,59.26,26.52Z"/>
                    </svg>
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <!--Input de Apellido-->
                <p class="mt-2 mb-2">Apellido</p>
                <div class="w-4/5 relative">
                    <label for="Apellido"></label>
                    <input asp-for="Apellido" class="pl-12 text-black w-full h-12 rounded-full bg-white outline-none" name="Apellido" type="text" required >
                    <svg class="absolute pr-2" id="punto" data-name="Capa 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 242.39 68.06">
                        <circle class="cls-1" cx="34.03" cy="34.03" r="34.03"/>
                        <circle class="cls-1" cx="121.19" cy="34.03" r="34.03"/>
                        <circle class="cls-1" cx="208.36" cy="34.03" r="34.03"/>
                    </svg>
                    <span asp-validation-for="Apellido" class="text-danger"></span>
                </div>
                <!--Input de Username-->
                <p class="mt-2 mb-2">Username</p> 
                <div class="w-4/5 relative">
                    <label for="NombreUsuario"></label>
                    <input asp-for="NombreUsuario" class="pl-12 text-black w-full h-12 rounded-full bg-white outline-none" name="NombreUsuario" type="text" required >
                    <svg class="absolute pr-2" id="punto" data-name="Capa 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 242.39 68.06">
                        <circle class="cls-1" cx="34.03" cy="34.03" r="34.03"/>
                        <circle class="cls-1" cx="121.19" cy="34.03" r="34.03"/>
                        <circle class="cls-1" cx="208.36" cy="34.03" r="34.03"/>
                    </svg>
                    <span asp-validation-for="NombreUsuario" class="text-danger"></span>
                    @Html.ValidationMessageFor(model => model.NombreUsuario, "", new { @class = "text-danger" })
                </div>
                <div class="w-5/6 mt-2 flex justify-between">
                    <p class="ml-4 text-sm">recordar</p>
                    <p class="mr-4 text-sm">¿olvidaste tu contraeña?</p>
                </div>
                <button class="mt-8 py-2 px-4 rounded-full mb-4 text-white bg-azul h-10 w-44 flex items-center justify-center">continuar</button>
            </form>
            <a asp-action="Login" asp-controller="Register" class="justify-center items-center flex w-44 text-azul bg-white px-4 py-2 rounded-full">Inicia Sesion</a>
        </div>
    </section>    
</body>

Backend/Views/Register/Register_2.cshtml
@model BackEnd.Models.Register_2ViewModel;
<body id="body" class="h-screen w-full flex justify-center">
    <section class="h-full w-5/12 flex justify-center items-center">
        <div id="login" class="flex flex-col items-center h-4/5 w-full text-xl font-bold text-white rounded-3xl text-center bg-white/50">
            <h1 class="mt-8 mb-12 text-4xl font-bold">Registrate</h1>
            <form asp-action="Register_2" asp-controller="Register" class="w-4/6 mt-6 flex justify-center items-center flex-col" method="post">
                <p class="mb-2">Email</p>
                <!--Input de Email-->
                <div class="w-4/5 relative">
                    <label for="Email"></label>
                    <input asp-for="Email" class="pl-12 text-black w-full h-12 rounded-full bg-white outline-none" name="Email" type="text" required >
                    <svg class="absolute pr-2" id="correo" data-name="Capa 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 53.11 42.44">
                        <path class="cls-1" d="M50.81,42.44c1.27,0,2.3-1.65,2.3-3.68V15.81c0-2.64-1.69-4.43-3.21-3.38l-16.44,11.28c-4.16,2.86-9.66,2.86-13.82,0L3.21,12.42c-1.52-1.04-3.21.74-3.21,3.38v22.95c0,2.03,1.03,3.68,2.3,3.68h48.51Z"/>
                        <path class="cls-1" d="M48.32,0c1.27,0,2.3,1.65,2.3,3.68h0c0,1.47-.55,2.8-1.39,3.38l-16.44,12.52c-3.68,2.8-8.78,2.8-12.46,0L3.89,7.07c-.85-.58-1.39-1.91-1.39-3.38h0c0-2.03,1.03-3.68,2.3-3.68h43.52Z"/>
                    </svg>
                    <span asp-validation-for="Email" class="text-danger"></span>
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
                <!--Input de Contraseña-->
                <p class="mt-2 mb-2">Contrasena</p>
                <div class="w-4/5 relative">
                    <label for="password"></label>
                    <input asp-for="Contrasena" class="pl-12 text-black w-full h-12 rounded-full bg-white outline-none" name="Contrasena" type="password" required>
                    <svg class="absolute pr-2" id="candado" data-name="Capa 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 113.08 143.06">
                        <rect class="cls-1" y="46.57" width="113.08" height="96.49" rx="16.8" ry="16.8"/>
                        <path class="cls-2" d="M50.42,108.74l.09-9.25c.03-3.42-1.82-6.62-4.87-8.15-2.37-1.19-4.66-3.81-4.5-9.51.3-10.55,12.9-10.17,15.08-10.03.22.01.43.01.64,0,2.18-.15,14.77-.53,15.08,10.03.16,5.7-2.13,8.32-4.5,9.51-3.05,1.53-4.91,4.74-4.87,8.15l.09,9.25c0,1.34-.48,2.64-1.39,3.62l-.85.92c-2.09,2.27-5.66,2.27-7.75,0l-.85-.92c-.91-.99-1.41-2.28-1.39-3.62h-.01Z"/>
                        <path class="cls-1" d="M79.91,46.57v-8.55c-.36-11.8-8.09-22.67-23.37-23.04-15.28.37-23.02,11.24-23.37,23.04v8.55h-14.94v-8.25C18.22,17.16,35.38,0,56.54,0h0s0,0,0,0c21.16,0,38.32,17.16,38.32,38.32v8.25h-14.94Z"/>
                    </svg>
                    <span asp-validation-for="Contrasena" class="text-danger"></span>
                </div>
                <!--Input de Repetir Contraseña-->
                <p class="mt-2 mb-2">Repetir Contraseña</p>
                <div class="w-4/5 relative">
                    <label for="password"></label>
                    <input asp-for="RepetirContrasena" class="pl-12 text-black w-full h-12 rounded-full bg-white outline-none" name="RepetirContrasena" type="password" required>
                    <svg class="absolute pr-2" id="candado" data-name="Capa 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 113.08 143.06">
                        <rect class="cls-1" y="46.57" width="113.08" height="96.49" rx="16.8" ry="16.8"/>
                        <path class="cls-2" d="M50.42,108.74l.09-9.25c.03-3.42-1.82-6.62-4.87-8.15-2.37-1.19-4.66-3.81-4.5-9.51.3-10.55,12.9-10.17,15.08-10.03.22.01.43.01.64,0,2.18-.15,14.77-.53,15.08,10.03.16,5.7-2.13,8.32-4.5,9.51-3.05,1.53-4.91,4.74-4.87,8.15l.09,9.25c0,1.34-.48,2.64-1.39,3.62l-.85.92c-2.09,2.27-5.66,2.27-7.75,0l-.85-.92c-.91-.99-1.41-2.28-1.39-3.62h-.01Z"/>
                        <path class="cls-1" d="M79.91,46.57v-8.55c-.36-11.8-8.09-22.67-23.37-23.04-15.28.37-23.02,11.24-23.37,23.04v8.55h-14.94v-8.25C18.22,17.16,35.38,0,56.54,0h0s0,0,0,0c21.16,0,38.32,17.16,38.32,38.32v8.25h-14.94Z"/>
                    </svg>
                    <span asp-validation-for="RepetirContrasena" class="text-danger"></span>
                </div>
                <div class="w-5/6 mt-2 flex justify-between">
                    <p class="ml-4 text-sm">recordar</p>
                    <p class="mr-4 text-sm">¿olvidaste tu contraeña?</p>
                </div>
                <button class="mt-8 py-2 px-4 rounded-full mb-4 text-white bg-azul h-10 w-44 flex items-center justify-center">Registrate</button>
            </form>
            <a asp-action="Login" asp-controller="Register" class="justify-center items-center flex w-44 text-azul bg-white px-4 py-2 rounded-full">Inicia Sesion</a>
        </div>
    </section>
</body>